services:
  postgres:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA=${DB_DATA}
    ports:
      - ${DB_PORT}:5432

  backend:
    container_name: backend
    build: backend/
    volumes:
      - ./backend:/code/
    depends_on:
      - postgres
    environment:
      - PORT=${BACKEND_PORT}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  frontend:
    container_name: frontend
    build: frontend/
    volumes:
      - ./frontend:/code/
    depends_on:
      - backend
    environment:
      - PORT=${FRONTEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}